param([string]$CivPath='')
$ErrorActionPreference='Stop'
$Internal=Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
. (Join-Path $Internal 'LekTools.ps1')
try {
 if(Test-LEKCivRunning){throw 'Civilization V appears to be running. Close it before uninstalling.'}; $civ=Find-LEKCivV $CivPath; if(!$civ){throw 'Civilization V install folder not found.'}
 $items=@(@{P=Join-LEKPath $civ 'Assets\DLC\UI_bc1\Improvements\SocialPolicyPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_POLICY_V04_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_POLICY_V04_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\LeagueOverview.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_LEAGUE_V04_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_LEAGUE_V04_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChoosePantheonPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_PANTHEON_V05_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_PANTHEON_V05_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseReligionPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_RELIGION_V06_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_RELIGION_V06_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseFreeItem.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_FREEITEM_V07_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_FREEITEM_V07_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseFaithGreatPerson.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_FAITHGP_V07_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_FAITHGP_V07_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseMayaBonus.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_MAYA_V07_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_MAYA_V07_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseArchaeologyPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_ARCHAEOLOGY_V07_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_ARCHAEOLOGY_V07_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\DeclareWarPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_CITYCAPTURE_V07_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_CITYCAPTURE_V07_END'},@{P=Join-LEKPath $civ 'Assets\DLC\Expansion2\UI\InGame\Popups\ChooseIdeologyPopup.lua';B='-- LEK_EXT_SPACE_AUTOPILOT_IDEOLOGY_V08_BEGIN';E='-- LEK_EXT_SPACE_AUTOPILOT_IDEOLOGY_V08_END'})
 foreach($i in $items){if(Test-LEKPath $i.P){$t=[IO.File]::ReadAllText($i.P); Write-LEKUtf8NoBom $i.P (Remove-LEKMarkedBlock $t $i.B $i.E)}}
 Write-Host 'SPACE AUTOPILOT POLICY/CONGRESS v0.8 REMOVED.' -ForegroundColor Green
} catch {Write-Host ('ERROR: '+$_.Exception.Message) -ForegroundColor Red; exit 1}
